// Code generated by a dev-time script from docs/go/02_storage_protobuf.md §2.2/§2.3
// (walgit.v1 schema); the output is checked in per doc 02 §Decisions. The schema is frozen
// and append-only; regenerate only through a spec amendment. DO NOT hand-edit field numbers.
//
// Hand-rolled proto3 wire codec: same tags, varints, submessage lengths, map entries and
// Timestamp encoding as any conformant implementation (prost, protoc). No reflection, no
// google.golang.org/protobuf. Marshal/Unmarshal are pure functions over their arguments.
package proto

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"math"
	"sort"
	"unicode/utf8"

	"git.packden.us/crueber/walhub/internal/store"
)

// ErrTruncated: input ended mid-tag, mid-length or mid-value (§2.3.1).
var ErrTruncated = errors.New("proto: truncated message")

// ErrInvalid: structurally malformed wire data (bad wire type, group markers, varint
// overflow, invalid UTF-8 in a string).
var ErrInvalid = errors.New("proto: invalid wire data")

// ---- low-level helpers ----

func uvarintLen(v uint64) int {
	var tmp [binary.MaxVarintLen64]byte
	return binary.PutUvarint(tmp[:], v)
}

// sizeTag: encoded length of one field tag. Every field number in the frozen schema is
// < 16, so this is always 1; computed anyway so a future schema bump cannot silently drift.
func sizeTag(num uint64) int { return uvarintLen(num << 3) }

func sizeLen(n int) int { return uvarintLen(uint64(n)) }

func appendString(buf []byte, num uint64, s string) []byte {
	buf = binary.AppendUvarint(buf, num<<3|2)
	buf = binary.AppendUvarint(buf, uint64(len(s)))
	return append(buf, s...)
}

// submessager is implemented by every message type in this package.
type submessager interface {
	size() int
	AppendTo([]byte) []byte
}

func appendSub(buf []byte, num uint64, m submessager) []byte {
	buf = binary.AppendUvarint(buf, num<<3|2)
	buf = binary.AppendUvarint(buf, uint64(m.size()))
	return m.AppendTo(buf)
}

func sizeSub(m submessager) int {
	sz := m.size()
	return 1 + sizeLen(sz) + sz
}

// map<string,string>: one tag (wire type 2) per entry; each entry is a submessage with
// field 1 = key, field 2 = value; a default-valued side is omitted (§2.3.1). Encoded in
// sorted key order — deterministic; entry order is not semantically significant to any
// conformant decoder.

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func mapEntrySize(k, v string) int {
	n := 0
	if k != "" {
		n += 2 + len(k)
	}
	if v != "" {
		n += 2 + len(v)
	}
	return n
}

func appendMapEntry(buf []byte, k, v string) []byte {
	if k != "" {
		buf = appendString(buf, 1, k)
	}
	if v != "" {
		buf = appendString(buf, 2, v)
	}
	return buf
}

func decodeMapEntry(b []byte) (string, string, error) {
	var k, v string
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return "", "", err
		}
		switch {
		case f == 1 && wt == 2:
			if k, err = d.str(); err != nil {
				return "", "", err
			}
		case f == 2 && wt == 2:
			if v, err = d.str(); err != nil {
				return "", "", err
			}
		default:
			if err := d.skip(wt); err != nil {
				return "", "", err
			}
		}
	}
	return k, v, nil
}

// PutZigZag / ZigZag: zigzag mapping kept for completeness (§2.3.1). The walgit.v1 schema
// has no sint32/sint64 fields, so nothing in this package calls them today.
func PutZigZag(v int64) uint64 { return uint64(v<<1) ^ uint64(v>>63) }

func ZigZag(v uint64) int64 { return int64(v>>1) ^ -int64(v&1) }

// ---- decoder ----

type dec struct {
	b   []byte
	pos int
}

func (d *dec) more() bool { return d.pos < len(d.b) }

func (d *dec) uvarint() (uint64, error) {
	var v uint64
	for shift := uint(0); ; shift += 7 {
		if d.pos >= len(d.b) {
			return 0, ErrTruncated
		}
		if shift >= 64 {
			return 0, ErrInvalid // varint longer than 10 bytes
		}
		b := d.b[d.pos]
		d.pos++
		if b < 0x80 {
			if shift == 63 && b > 1 {
				return 0, ErrInvalid // value overflows 64 bits
			}
			return v | uint64(b)<<shift, nil
		}
		v |= uint64(b&0x7f) << shift
	}
}

func (d *dec) tag() (num uint64, wt int, err error) {
	v, err := d.uvarint()
	if err != nil {
		return 0, 0, err
	}
	num, wt = v>>3, int(v&7)
	if num == 0 {
		return 0, 0, ErrInvalid // field number 0 is never valid
	}
	return num, wt, nil
}

func (d *dec) raw() ([]byte, error) {
	ln, err := d.uvarint()
	if err != nil {
		return nil, err
	}
	if ln > uint64(len(d.b)-d.pos) {
		return nil, ErrTruncated
	}
	s := d.b[d.pos : d.pos+int(ln)]
	d.pos += int(ln)
	return s, nil
}

func (d *dec) str() (string, error) {
	b, err := d.raw()
	if err != nil {
		return "", err
	}
	if !utf8.Valid(b) {
		return "", ErrInvalid
	}
	return string(b), nil
}

func (d *dec) f64() (float64, error) {
	if len(d.b)-d.pos < 8 {
		return 0, ErrTruncated
	}
	v := math.Float64frombits(binary.LittleEndian.Uint64(d.b[d.pos:]))
	d.pos += 8
	return v, nil
}

// skip consumes one unknown field per its wire type (§2.3.1). Groups (3/4) are invalid:
// the schema has no groups and no conformant writer emits them.
func (d *dec) skip(wt int) error {
	switch wt {
	case 0:
		_, err := d.uvarint()
		return err
	case 1:
		if len(d.b)-d.pos < 8 {
			return ErrTruncated
		}
		d.pos += 8
		return nil
	case 2:
		_, err := d.raw()
		return err
	case 5:
		if len(d.b)-d.pos < 4 {
			return ErrTruncated
		}
		d.pos += 4
		return nil
	default: // 3, 4 (groups) and any future wire type
		return ErrInvalid
	}
}

// ---- Timestamp ----

func (m *Timestamp) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Seconds != 0 {
		n += sizeTag(1) + uvarintLen(uint64(m.Seconds))
	}
	if m.Nanos != 0 {
		n += sizeTag(2) + uvarintLen(uint64(int64(m.Nanos)))
	}
	return n
}

func (m *Timestamp) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *Timestamp) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Seconds != 0 {
		buf = binary.AppendUvarint(buf, uint64(1)<<3|0)
		buf = binary.AppendUvarint(buf, uint64(m.Seconds))
	}
	if m.Nanos != 0 {
		buf = binary.AppendUvarint(buf, uint64(2)<<3|0)
		buf = binary.AppendUvarint(buf, uint64(int64(m.Nanos)))
	}
	return buf
}

func (m *Timestamp) Unmarshal(b []byte) error {
	*m = Timestamp{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *Timestamp) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seconds = int64(v)
		case f == 2 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Nanos = int32(v)
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *Timestamp) Size() int { return m.size() }

// ---- Manifest ----

func (m *Manifest) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.FormatVersion != 0 {
		n += sizeTag(1) + uvarintLen(uint64(m.FormatVersion))
	}
	if m.Repo != "" {
		n += sizeTag(2) + sizeLen(len(m.Repo)) + len(m.Repo)
	}
	if m.ObjectFormat != "" {
		n += sizeTag(3) + sizeLen(len(m.ObjectFormat)) + len(m.ObjectFormat)
	}
	if m.HeadSeq != 0 {
		n += sizeTag(4) + uvarintLen(m.HeadSeq)
	}
	if m.MinSeq != 0 {
		n += sizeTag(5) + uvarintLen(m.MinSeq)
	}
	if m.Checkpoint != nil {
		n += sizeSub(m.Checkpoint)
	}
	for _, e := range m.LogSegments {
		if e != nil {
			n += sizeSub(e)
		}
	}
	for _, e := range m.Packs {
		if e != nil {
			n += sizeSub(e)
		}
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		n += sizeSub(m.UpdatedAt)
	}
	if m.Writer != "" {
		n += sizeTag(10) + sizeLen(len(m.Writer)) + len(m.Writer)
	}
	if m.Revision != 0 {
		n += sizeTag(11) + uvarintLen(m.Revision)
	}
	if m.Settings != nil {
		n += sizeSub(m.Settings)
	}
	return n
}

func (m *Manifest) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *Manifest) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.FormatVersion != 0 {
		buf = binary.AppendUvarint(buf, uint64(1)<<3|0)
		buf = binary.AppendUvarint(buf, uint64(m.FormatVersion))
	}
	if m.Repo != "" {
		buf = appendString(buf, 2, m.Repo)
	}
	if m.ObjectFormat != "" {
		buf = appendString(buf, 3, m.ObjectFormat)
	}
	if m.HeadSeq != 0 {
		buf = binary.AppendUvarint(buf, uint64(4)<<3|0)
		buf = binary.AppendUvarint(buf, m.HeadSeq)
	}
	if m.MinSeq != 0 {
		buf = binary.AppendUvarint(buf, uint64(5)<<3|0)
		buf = binary.AppendUvarint(buf, m.MinSeq)
	}
	if m.Checkpoint != nil {
		buf = appendSub(buf, 6, m.Checkpoint)
	}
	for _, e := range m.LogSegments {
		if e != nil {
			buf = appendSub(buf, 7, e)
		}
	}
	for _, e := range m.Packs {
		if e != nil {
			buf = appendSub(buf, 8, e)
		}
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		buf = appendSub(buf, 9, m.UpdatedAt)
	}
	if m.Writer != "" {
		buf = appendString(buf, 10, m.Writer)
	}
	if m.Revision != 0 {
		buf = binary.AppendUvarint(buf, uint64(11)<<3|0)
		buf = binary.AppendUvarint(buf, m.Revision)
	}
	if m.Settings != nil {
		buf = appendSub(buf, 12, m.Settings)
	}
	return buf
}

func (m *Manifest) Unmarshal(b []byte) error {
	*m = Manifest{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *Manifest) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.FormatVersion = uint32(v)
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Repo = s
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.ObjectFormat = s
		case f == 4 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.HeadSeq = v
		case f == 5 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.MinSeq = v
		case f == 6 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &CheckpointRef{}
			}
			if err := m.Checkpoint.unmarshal(sub); err != nil {
				return err
			}
		case f == 7 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &LogSegmentRef{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.LogSegments = append(m.LogSegments, e)
		case f == 8 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &PackRef{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.Packs = append(m.Packs, e)
		case f == 9 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = &Timestamp{}
			}
			if err := m.UpdatedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 10 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Writer = s
		case f == 11 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Revision = v
		case f == 12 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.Settings == nil {
				m.Settings = &RepoSettings{}
			}
			if err := m.Settings.unmarshal(sub); err != nil {
				return err
			}
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *Manifest) Size() int { return m.size() }

// ---- RepoSettings ----

func (m *RepoSettings) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Toml != "" {
		n += sizeTag(1) + sizeLen(len(m.Toml)) + len(m.Toml)
	}
	if m.Revision != 0 {
		n += sizeTag(2) + uvarintLen(m.Revision)
	}
	if m.Author != "" {
		n += sizeTag(3) + sizeLen(len(m.Author)) + len(m.Author)
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		n += sizeSub(m.UpdatedAt)
	}
	if m.Message != "" {
		n += sizeTag(5) + sizeLen(len(m.Message)) + len(m.Message)
	}
	return n
}

func (m *RepoSettings) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *RepoSettings) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Toml != "" {
		buf = appendString(buf, 1, m.Toml)
	}
	if m.Revision != 0 {
		buf = binary.AppendUvarint(buf, uint64(2)<<3|0)
		buf = binary.AppendUvarint(buf, m.Revision)
	}
	if m.Author != "" {
		buf = appendString(buf, 3, m.Author)
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		buf = appendSub(buf, 4, m.UpdatedAt)
	}
	if m.Message != "" {
		buf = appendString(buf, 5, m.Message)
	}
	return buf
}

func (m *RepoSettings) Unmarshal(b []byte) error {
	*m = RepoSettings{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *RepoSettings) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Toml = s
		case f == 2 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Revision = v
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Author = s
		case f == 4 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = &Timestamp{}
			}
			if err := m.UpdatedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 5 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Message = s
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *RepoSettings) Size() int { return m.size() }

// ---- LogSegmentRef ----

func (m *LogSegmentRef) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Key != "" {
		n += sizeTag(1) + sizeLen(len(m.Key)) + len(m.Key)
	}
	if m.FirstSeq != 0 {
		n += sizeTag(2) + uvarintLen(m.FirstSeq)
	}
	if m.LastSeq != 0 {
		n += sizeTag(3) + uvarintLen(m.LastSeq)
	}
	if m.Size != 0 {
		n += sizeTag(4) + uvarintLen(m.Size)
	}
	if m.Sealed {
		n += sizeTag(5) + 1
	}
	return n
}

func (m *LogSegmentRef) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *LogSegmentRef) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Key != "" {
		buf = appendString(buf, 1, m.Key)
	}
	if m.FirstSeq != 0 {
		buf = binary.AppendUvarint(buf, uint64(2)<<3|0)
		buf = binary.AppendUvarint(buf, m.FirstSeq)
	}
	if m.LastSeq != 0 {
		buf = binary.AppendUvarint(buf, uint64(3)<<3|0)
		buf = binary.AppendUvarint(buf, m.LastSeq)
	}
	if m.Size != 0 {
		buf = binary.AppendUvarint(buf, uint64(4)<<3|0)
		buf = binary.AppendUvarint(buf, m.Size)
	}
	if m.Sealed {
		buf = binary.AppendUvarint(buf, uint64(5)<<3|0)
		buf = append(buf, 1)
	}
	return buf
}

func (m *LogSegmentRef) Unmarshal(b []byte) error {
	*m = LogSegmentRef{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *LogSegmentRef) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Key = s
		case f == 2 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.FirstSeq = v
		case f == 3 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.LastSeq = v
		case f == 4 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Size = v
		case f == 5 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Sealed = v != 0
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// EncodedSize returns the exact encoded byte length (equals len(Marshal(m)));
// named EncodedSize because the wire field %s.Size claims the identifier.
func (m *LogSegmentRef) EncodedSize() int { return m.size() }

// ---- PackRef ----

func (m *PackRef) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Checksum != "" {
		n += sizeTag(1) + sizeLen(len(m.Checksum)) + len(m.Checksum)
	}
	if m.PackSize != 0 {
		n += sizeTag(2) + uvarintLen(m.PackSize)
	}
	if m.IdxSize != 0 {
		n += sizeTag(3) + uvarintLen(m.IdxSize)
	}
	if m.HasRev {
		n += sizeTag(4) + 1
	}
	if m.HasBitmap {
		n += sizeTag(5) + 1
	}
	if m.ObjectCount != 0 {
		n += sizeTag(6) + uvarintLen(m.ObjectCount)
	}
	if m.Seq != 0 {
		n += sizeTag(7) + uvarintLen(m.Seq)
	}
	if m.Tier != 0 {
		n += sizeTag(8) + uvarintLen(uint64(m.Tier))
	}
	if m.HasCommitGraph {
		n += sizeTag(9) + 1
	}
	if m.Kind != 0 {
		n += sizeTag(10) + uvarintLen(uint64(uint32(m.Kind)))
	}
	if m.DerivedFrom != "" {
		n += sizeTag(11) + sizeLen(len(m.DerivedFrom)) + len(m.DerivedFrom)
	}
	return n
}

func (m *PackRef) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *PackRef) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Checksum != "" {
		buf = appendString(buf, 1, m.Checksum)
	}
	if m.PackSize != 0 {
		buf = binary.AppendUvarint(buf, uint64(2)<<3|0)
		buf = binary.AppendUvarint(buf, m.PackSize)
	}
	if m.IdxSize != 0 {
		buf = binary.AppendUvarint(buf, uint64(3)<<3|0)
		buf = binary.AppendUvarint(buf, m.IdxSize)
	}
	if m.HasRev {
		buf = binary.AppendUvarint(buf, uint64(4)<<3|0)
		buf = append(buf, 1)
	}
	if m.HasBitmap {
		buf = binary.AppendUvarint(buf, uint64(5)<<3|0)
		buf = append(buf, 1)
	}
	if m.ObjectCount != 0 {
		buf = binary.AppendUvarint(buf, uint64(6)<<3|0)
		buf = binary.AppendUvarint(buf, m.ObjectCount)
	}
	if m.Seq != 0 {
		buf = binary.AppendUvarint(buf, uint64(7)<<3|0)
		buf = binary.AppendUvarint(buf, m.Seq)
	}
	if m.Tier != 0 {
		buf = binary.AppendUvarint(buf, uint64(8)<<3|0)
		buf = binary.AppendUvarint(buf, uint64(m.Tier))
	}
	if m.HasCommitGraph {
		buf = binary.AppendUvarint(buf, uint64(9)<<3|0)
		buf = append(buf, 1)
	}
	if m.Kind != 0 {
		buf = binary.AppendUvarint(buf, uint64(10)<<3|0)
		buf = binary.AppendUvarint(buf, uint64(uint32(m.Kind)))
	}
	if m.DerivedFrom != "" {
		buf = appendString(buf, 11, m.DerivedFrom)
	}
	return buf
}

func (m *PackRef) Unmarshal(b []byte) error {
	*m = PackRef{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *PackRef) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Checksum = s
		case f == 2 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.PackSize = v
		case f == 3 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.IdxSize = v
		case f == 4 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.HasRev = v != 0
		case f == 5 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.HasBitmap = v != 0
		case f == 6 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.ObjectCount = v
		case f == 7 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seq = v
		case f == 8 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Tier = uint32(v)
		case f == 9 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.HasCommitGraph = v != 0
		case f == 10 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Kind = PackKind(int32(v))
		case f == 11 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.DerivedFrom = s
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *PackRef) Size() int { return m.size() }

// ---- LogEntry ----

func (m *LogEntry) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Seq != 0 {
		n += sizeTag(1) + uvarintLen(m.Seq)
	}
	if m.Kind != 0 {
		n += sizeTag(2) + uvarintLen(uint64(uint32(m.Kind)))
	}
	if m.Pack != nil {
		n += sizeSub(m.Pack)
	}
	if m.Txn != nil {
		n += sizeSub(m.Txn)
	}
	for _, s := range m.Supersedes {
		n += sizeTag(5) + sizeLen(len(s)) + len(s)
	}
	if m.Checkpoint != nil {
		n += sizeSub(m.Checkpoint)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		n += sizeSub(m.CreatedAt)
	}
	if m.Writer != "" {
		n += sizeTag(8) + sizeLen(len(m.Writer)) + len(m.Writer)
	}
	if len(m.Meta) > 0 {
		for _, k := range sortedKeys(m.Meta) {
			es := mapEntrySize(k, m.Meta[k])
			n += sizeTag(9) + sizeLen(es) + es
		}
	}
	if m.Settings != nil {
		n += sizeSub(m.Settings)
	}
	return n
}

func (m *LogEntry) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *LogEntry) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Seq != 0 {
		buf = binary.AppendUvarint(buf, uint64(1)<<3|0)
		buf = binary.AppendUvarint(buf, m.Seq)
	}
	if m.Kind != 0 {
		buf = binary.AppendUvarint(buf, uint64(2)<<3|0)
		buf = binary.AppendUvarint(buf, uint64(uint32(m.Kind)))
	}
	if m.Pack != nil {
		buf = appendSub(buf, 3, m.Pack)
	}
	if m.Txn != nil {
		buf = appendSub(buf, 4, m.Txn)
	}
	for _, s := range m.Supersedes {
		buf = appendString(buf, 5, s)
	}
	if m.Checkpoint != nil {
		buf = appendSub(buf, 6, m.Checkpoint)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		buf = appendSub(buf, 7, m.CreatedAt)
	}
	if m.Writer != "" {
		buf = appendString(buf, 8, m.Writer)
	}
	for _, k := range sortedKeys(m.Meta) {
		buf = binary.AppendUvarint(buf, uint64(9)<<3|2)
		buf = binary.AppendUvarint(buf, uint64(mapEntrySize(k, m.Meta[k])))
		buf = appendMapEntry(buf, k, m.Meta[k])
	}
	if m.Settings != nil {
		buf = appendSub(buf, 10, m.Settings)
	}
	return buf
}

func (m *LogEntry) Unmarshal(b []byte) error {
	*m = LogEntry{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *LogEntry) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seq = v
		case f == 2 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Kind = EntryKind(int32(v))
		case f == 3 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.Pack == nil {
				m.Pack = &PackRef{}
			}
			if err := m.Pack.unmarshal(sub); err != nil {
				return err
			}
		case f == 4 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.Txn == nil {
				m.Txn = &RefTransaction{}
			}
			if err := m.Txn.unmarshal(sub); err != nil {
				return err
			}
		case f == 5 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Supersedes = append(m.Supersedes, s)
		case f == 6 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &CheckpointRef{}
			}
			if err := m.Checkpoint.unmarshal(sub); err != nil {
				return err
			}
		case f == 7 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &Timestamp{}
			}
			if err := m.CreatedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 8 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Writer = s
		case f == 9 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			k, v, err := decodeMapEntry(sub)
			if err != nil {
				return err
			}
			if m.Meta == nil {
				m.Meta = make(map[string]string, 1)
			}
			m.Meta[k] = v
		case f == 10 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.Settings == nil {
				m.Settings = &RepoSettings{}
			}
			if err := m.Settings.unmarshal(sub); err != nil {
				return err
			}
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *LogEntry) Size() int { return m.size() }

// ---- RefUpdate ----

func (m *RefUpdate) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Name != "" {
		n += sizeTag(1) + sizeLen(len(m.Name)) + len(m.Name)
	}
	if m.OldOid != "" {
		n += sizeTag(2) + sizeLen(len(m.OldOid)) + len(m.OldOid)
	}
	if m.NewOid != "" {
		n += sizeTag(3) + sizeLen(len(m.NewOid)) + len(m.NewOid)
	}
	if m.NewSymbolicTarget != "" {
		n += sizeTag(4) + sizeLen(len(m.NewSymbolicTarget)) + len(m.NewSymbolicTarget)
	}
	if m.NewPeeled != "" {
		n += sizeTag(5) + sizeLen(len(m.NewPeeled)) + len(m.NewPeeled)
	}
	return n
}

func (m *RefUpdate) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *RefUpdate) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Name != "" {
		buf = appendString(buf, 1, m.Name)
	}
	if m.OldOid != "" {
		buf = appendString(buf, 2, m.OldOid)
	}
	if m.NewOid != "" {
		buf = appendString(buf, 3, m.NewOid)
	}
	if m.NewSymbolicTarget != "" {
		buf = appendString(buf, 4, m.NewSymbolicTarget)
	}
	if m.NewPeeled != "" {
		buf = appendString(buf, 5, m.NewPeeled)
	}
	return buf
}

func (m *RefUpdate) Unmarshal(b []byte) error {
	*m = RefUpdate{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *RefUpdate) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Name = s
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.OldOid = s
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.NewOid = s
		case f == 4 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.NewSymbolicTarget = s
		case f == 5 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.NewPeeled = s
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *RefUpdate) Size() int { return m.size() }

// ---- RefTransaction ----

func (m *RefTransaction) size() int {
	if m == nil {
		return 0
	}
	n := 0
	for _, e := range m.Updates {
		if e != nil {
			n += sizeSub(e)
		}
	}
	for _, s := range m.PushOptions {
		n += sizeTag(2) + sizeLen(len(s)) + len(s)
	}
	if m.Atomic {
		n += sizeTag(3) + 1
	}
	return n
}

func (m *RefTransaction) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *RefTransaction) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	for _, e := range m.Updates {
		if e != nil {
			buf = appendSub(buf, 1, e)
		}
	}
	for _, s := range m.PushOptions {
		buf = appendString(buf, 2, s)
	}
	if m.Atomic {
		buf = binary.AppendUvarint(buf, uint64(3)<<3|0)
		buf = append(buf, 1)
	}
	return buf
}

func (m *RefTransaction) Unmarshal(b []byte) error {
	*m = RefTransaction{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *RefTransaction) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &RefUpdate{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.Updates = append(m.Updates, e)
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.PushOptions = append(m.PushOptions, s)
		case f == 3 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Atomic = v != 0
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *RefTransaction) Size() int { return m.size() }

// ---- Checkpoint ----

func (m *Checkpoint) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Seq != 0 {
		n += sizeTag(1) + uvarintLen(m.Seq)
	}
	if m.ObjectFormat != "" {
		n += sizeTag(2) + sizeLen(len(m.ObjectFormat)) + len(m.ObjectFormat)
	}
	for _, e := range m.Packs {
		if e != nil {
			n += sizeSub(e)
		}
	}
	if m.RefsKey != "" {
		n += sizeTag(4) + sizeLen(len(m.RefsKey)) + len(m.RefsKey)
	}
	if m.RefCount != 0 {
		n += sizeTag(5) + uvarintLen(m.RefCount)
	}
	if m.BundleKey != "" {
		n += sizeTag(6) + sizeLen(len(m.BundleKey)) + len(m.BundleKey)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		n += sizeSub(m.CreatedAt)
	}
	if m.Writer != "" {
		n += sizeTag(8) + sizeLen(len(m.Writer)) + len(m.Writer)
	}
	return n
}

func (m *Checkpoint) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *Checkpoint) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Seq != 0 {
		buf = binary.AppendUvarint(buf, uint64(1)<<3|0)
		buf = binary.AppendUvarint(buf, m.Seq)
	}
	if m.ObjectFormat != "" {
		buf = appendString(buf, 2, m.ObjectFormat)
	}
	for _, e := range m.Packs {
		if e != nil {
			buf = appendSub(buf, 3, e)
		}
	}
	if m.RefsKey != "" {
		buf = appendString(buf, 4, m.RefsKey)
	}
	if m.RefCount != 0 {
		buf = binary.AppendUvarint(buf, uint64(5)<<3|0)
		buf = binary.AppendUvarint(buf, m.RefCount)
	}
	if m.BundleKey != "" {
		buf = appendString(buf, 6, m.BundleKey)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		buf = appendSub(buf, 7, m.CreatedAt)
	}
	if m.Writer != "" {
		buf = appendString(buf, 8, m.Writer)
	}
	return buf
}

func (m *Checkpoint) Unmarshal(b []byte) error {
	*m = Checkpoint{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *Checkpoint) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seq = v
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.ObjectFormat = s
		case f == 3 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &PackRef{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.Packs = append(m.Packs, e)
		case f == 4 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.RefsKey = s
		case f == 5 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.RefCount = v
		case f == 6 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.BundleKey = s
		case f == 7 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &Timestamp{}
			}
			if err := m.CreatedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 8 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Writer = s
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *Checkpoint) Size() int { return m.size() }

// ---- CheckpointRef ----

func (m *CheckpointRef) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Seq != 0 {
		n += sizeTag(1) + uvarintLen(m.Seq)
	}
	if m.Key != "" {
		n += sizeTag(2) + sizeLen(len(m.Key)) + len(m.Key)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		n += sizeSub(m.CreatedAt)
	}
	if m.FirstStateAt != nil && (m.FirstStateAt.Seconds != 0 || m.FirstStateAt.Nanos != 0) {
		n += sizeSub(m.FirstStateAt)
	}
	if m.AsOf != nil && (m.AsOf.Seconds != 0 || m.AsOf.Nanos != 0) {
		n += sizeSub(m.AsOf)
	}
	return n
}

func (m *CheckpointRef) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *CheckpointRef) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Seq != 0 {
		buf = binary.AppendUvarint(buf, uint64(1)<<3|0)
		buf = binary.AppendUvarint(buf, m.Seq)
	}
	if m.Key != "" {
		buf = appendString(buf, 2, m.Key)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		buf = appendSub(buf, 3, m.CreatedAt)
	}
	if m.FirstStateAt != nil && (m.FirstStateAt.Seconds != 0 || m.FirstStateAt.Nanos != 0) {
		buf = appendSub(buf, 4, m.FirstStateAt)
	}
	if m.AsOf != nil && (m.AsOf.Seconds != 0 || m.AsOf.Nanos != 0) {
		buf = appendSub(buf, 5, m.AsOf)
	}
	return buf
}

func (m *CheckpointRef) Unmarshal(b []byte) error {
	*m = CheckpointRef{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *CheckpointRef) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seq = v
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Key = s
		case f == 3 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &Timestamp{}
			}
			if err := m.CreatedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 4 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.FirstStateAt == nil {
				m.FirstStateAt = &Timestamp{}
			}
			if err := m.FirstStateAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 5 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.AsOf == nil {
				m.AsOf = &Timestamp{}
			}
			if err := m.AsOf.unmarshal(sub); err != nil {
				return err
			}
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *CheckpointRef) Size() int { return m.size() }

// ---- RefSnapshot ----

func (m *RefSnapshot) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Seq != 0 {
		n += sizeTag(1) + uvarintLen(m.Seq)
	}
	if m.ObjectFormat != "" {
		n += sizeTag(2) + sizeLen(len(m.ObjectFormat)) + len(m.ObjectFormat)
	}
	for _, e := range m.Refs {
		if e != nil {
			n += sizeSub(e)
		}
	}
	if m.HeadTarget != "" {
		n += sizeTag(4) + sizeLen(len(m.HeadTarget)) + len(m.HeadTarget)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		n += sizeSub(m.CreatedAt)
	}
	return n
}

func (m *RefSnapshot) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *RefSnapshot) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Seq != 0 {
		buf = binary.AppendUvarint(buf, uint64(1)<<3|0)
		buf = binary.AppendUvarint(buf, m.Seq)
	}
	if m.ObjectFormat != "" {
		buf = appendString(buf, 2, m.ObjectFormat)
	}
	for _, e := range m.Refs {
		if e != nil {
			buf = appendSub(buf, 3, e)
		}
	}
	if m.HeadTarget != "" {
		buf = appendString(buf, 4, m.HeadTarget)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		buf = appendSub(buf, 5, m.CreatedAt)
	}
	return buf
}

func (m *RefSnapshot) Unmarshal(b []byte) error {
	*m = RefSnapshot{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *RefSnapshot) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seq = v
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.ObjectFormat = s
		case f == 3 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &Ref{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.Refs = append(m.Refs, e)
		case f == 4 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.HeadTarget = s
		case f == 5 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &Timestamp{}
			}
			if err := m.CreatedAt.unmarshal(sub); err != nil {
				return err
			}
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *RefSnapshot) Size() int { return m.size() }

// ---- Ref ----

func (m *Ref) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Name != "" {
		n += sizeTag(1) + sizeLen(len(m.Name)) + len(m.Name)
	}
	if m.Oid != "" {
		n += sizeTag(2) + sizeLen(len(m.Oid)) + len(m.Oid)
	}
	if m.Peeled != "" {
		n += sizeTag(3) + sizeLen(len(m.Peeled)) + len(m.Peeled)
	}
	return n
}

func (m *Ref) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *Ref) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Name != "" {
		buf = appendString(buf, 1, m.Name)
	}
	if m.Oid != "" {
		buf = appendString(buf, 2, m.Oid)
	}
	if m.Peeled != "" {
		buf = appendString(buf, 3, m.Peeled)
	}
	return buf
}

func (m *Ref) Unmarshal(b []byte) error {
	*m = Ref{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *Ref) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Name = s
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Oid = s
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Peeled = s
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *Ref) Size() int { return m.size() }

// ---- Lease ----

func (m *Lease) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Holder != "" {
		n += sizeTag(1) + sizeLen(len(m.Holder)) + len(m.Holder)
	}
	if m.Purpose != "" {
		n += sizeTag(2) + sizeLen(len(m.Purpose)) + len(m.Purpose)
	}
	if m.AcquiredAt != nil && (m.AcquiredAt.Seconds != 0 || m.AcquiredAt.Nanos != 0) {
		n += sizeSub(m.AcquiredAt)
	}
	if m.ExpiresAt != nil && (m.ExpiresAt.Seconds != 0 || m.ExpiresAt.Nanos != 0) {
		n += sizeSub(m.ExpiresAt)
	}
	if m.Epoch != 0 {
		n += sizeTag(5) + uvarintLen(m.Epoch)
	}
	return n
}

func (m *Lease) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *Lease) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Holder != "" {
		buf = appendString(buf, 1, m.Holder)
	}
	if m.Purpose != "" {
		buf = appendString(buf, 2, m.Purpose)
	}
	if m.AcquiredAt != nil && (m.AcquiredAt.Seconds != 0 || m.AcquiredAt.Nanos != 0) {
		buf = appendSub(buf, 3, m.AcquiredAt)
	}
	if m.ExpiresAt != nil && (m.ExpiresAt.Seconds != 0 || m.ExpiresAt.Nanos != 0) {
		buf = appendSub(buf, 4, m.ExpiresAt)
	}
	if m.Epoch != 0 {
		buf = binary.AppendUvarint(buf, uint64(5)<<3|0)
		buf = binary.AppendUvarint(buf, m.Epoch)
	}
	return buf
}

func (m *Lease) Unmarshal(b []byte) error {
	*m = Lease{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *Lease) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Holder = s
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Purpose = s
		case f == 3 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.AcquiredAt == nil {
				m.AcquiredAt = &Timestamp{}
			}
			if err := m.AcquiredAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 4 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.ExpiresAt == nil {
				m.ExpiresAt = &Timestamp{}
			}
			if err := m.ExpiresAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 5 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Epoch = v
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *Lease) Size() int { return m.size() }

// ---- BundleList ----

func (m *BundleList) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Mode != "" {
		n += sizeTag(1) + sizeLen(len(m.Mode)) + len(m.Mode)
	}
	if m.Heuristic != "" {
		n += sizeTag(2) + sizeLen(len(m.Heuristic)) + len(m.Heuristic)
	}
	for _, e := range m.Bundles {
		if e != nil {
			n += sizeSub(e)
		}
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		n += sizeSub(m.UpdatedAt)
	}
	for _, e := range m.Skipped {
		if e != nil {
			n += sizeSub(e)
		}
	}
	return n
}

func (m *BundleList) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *BundleList) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Mode != "" {
		buf = appendString(buf, 1, m.Mode)
	}
	if m.Heuristic != "" {
		buf = appendString(buf, 2, m.Heuristic)
	}
	for _, e := range m.Bundles {
		if e != nil {
			buf = appendSub(buf, 3, e)
		}
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		buf = appendSub(buf, 4, m.UpdatedAt)
	}
	for _, e := range m.Skipped {
		if e != nil {
			buf = appendSub(buf, 5, e)
		}
	}
	return buf
}

func (m *BundleList) Unmarshal(b []byte) error {
	*m = BundleList{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *BundleList) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Mode = s
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Heuristic = s
		case f == 3 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &BundleEntry{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.Bundles = append(m.Bundles, e)
		case f == 4 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = &Timestamp{}
			}
			if err := m.UpdatedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 5 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &SkippedSlot{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.Skipped = append(m.Skipped, e)
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *BundleList) Size() int { return m.size() }

// ---- SkippedSlot ----

func (m *SkippedSlot) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Strategy != "" {
		n += sizeTag(1) + sizeLen(len(m.Strategy)) + len(m.Strategy)
	}
	if m.Slot != 0 {
		n += sizeTag(2) + uvarintLen(m.Slot)
	}
	if m.BaseID != "" {
		n += sizeTag(3) + sizeLen(len(m.BaseID)) + len(m.BaseID)
	}
	if m.AsOfSeq != 0 {
		n += sizeTag(4) + uvarintLen(m.AsOfSeq)
	}
	if m.Reason != "" {
		n += sizeTag(5) + sizeLen(len(m.Reason)) + len(m.Reason)
	}
	if m.At != nil && (m.At.Seconds != 0 || m.At.Nanos != 0) {
		n += sizeSub(m.At)
	}
	return n
}

func (m *SkippedSlot) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *SkippedSlot) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Strategy != "" {
		buf = appendString(buf, 1, m.Strategy)
	}
	if m.Slot != 0 {
		buf = binary.AppendUvarint(buf, uint64(2)<<3|0)
		buf = binary.AppendUvarint(buf, m.Slot)
	}
	if m.BaseID != "" {
		buf = appendString(buf, 3, m.BaseID)
	}
	if m.AsOfSeq != 0 {
		buf = binary.AppendUvarint(buf, uint64(4)<<3|0)
		buf = binary.AppendUvarint(buf, m.AsOfSeq)
	}
	if m.Reason != "" {
		buf = appendString(buf, 5, m.Reason)
	}
	if m.At != nil && (m.At.Seconds != 0 || m.At.Nanos != 0) {
		buf = appendSub(buf, 6, m.At)
	}
	return buf
}

func (m *SkippedSlot) Unmarshal(b []byte) error {
	*m = SkippedSlot{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *SkippedSlot) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Strategy = s
		case f == 2 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Slot = v
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.BaseID = s
		case f == 4 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.AsOfSeq = v
		case f == 5 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Reason = s
		case f == 6 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.At == nil {
				m.At = &Timestamp{}
			}
			if err := m.At.unmarshal(sub); err != nil {
				return err
			}
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *SkippedSlot) Size() int { return m.size() }

// ---- BundleEntry ----

func (m *BundleEntry) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.ID != "" {
		n += sizeTag(1) + sizeLen(len(m.ID)) + len(m.ID)
	}
	if m.Key != "" {
		n += sizeTag(2) + sizeLen(len(m.Key)) + len(m.Key)
	}
	if m.Strategy != "" {
		n += sizeTag(3) + sizeLen(len(m.Strategy)) + len(m.Strategy)
	}
	if m.Kind != "" {
		n += sizeTag(4) + sizeLen(len(m.Kind)) + len(m.Kind)
	}
	if m.CreationToken != 0 {
		n += sizeTag(5) + uvarintLen(m.CreationToken)
	}
	if m.Seq != 0 {
		n += sizeTag(6) + uvarintLen(m.Seq)
	}
	if m.Size != 0 {
		n += sizeTag(7) + uvarintLen(m.Size)
	}
	if m.BaseID != "" {
		n += sizeTag(8) + sizeLen(len(m.BaseID)) + len(m.BaseID)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		n += sizeSub(m.CreatedAt)
	}
	if m.Version != "" {
		n += sizeTag(10) + sizeLen(len(m.Version)) + len(m.Version)
	}
	for _, e := range m.Tips {
		if e != nil {
			n += sizeSub(e)
		}
	}
	if m.Slot != 0 {
		n += sizeTag(12) + uvarintLen(m.Slot)
	}
	if m.Filter != "" {
		n += sizeTag(13) + sizeLen(len(m.Filter)) + len(m.Filter)
	}
	return n
}

func (m *BundleEntry) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *BundleEntry) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.ID != "" {
		buf = appendString(buf, 1, m.ID)
	}
	if m.Key != "" {
		buf = appendString(buf, 2, m.Key)
	}
	if m.Strategy != "" {
		buf = appendString(buf, 3, m.Strategy)
	}
	if m.Kind != "" {
		buf = appendString(buf, 4, m.Kind)
	}
	if m.CreationToken != 0 {
		buf = binary.AppendUvarint(buf, uint64(5)<<3|0)
		buf = binary.AppendUvarint(buf, m.CreationToken)
	}
	if m.Seq != 0 {
		buf = binary.AppendUvarint(buf, uint64(6)<<3|0)
		buf = binary.AppendUvarint(buf, m.Seq)
	}
	if m.Size != 0 {
		buf = binary.AppendUvarint(buf, uint64(7)<<3|0)
		buf = binary.AppendUvarint(buf, m.Size)
	}
	if m.BaseID != "" {
		buf = appendString(buf, 8, m.BaseID)
	}
	if m.CreatedAt != nil && (m.CreatedAt.Seconds != 0 || m.CreatedAt.Nanos != 0) {
		buf = appendSub(buf, 9, m.CreatedAt)
	}
	if m.Version != "" {
		buf = appendString(buf, 10, m.Version)
	}
	for _, e := range m.Tips {
		if e != nil {
			buf = appendSub(buf, 11, e)
		}
	}
	if m.Slot != 0 {
		buf = binary.AppendUvarint(buf, uint64(12)<<3|0)
		buf = binary.AppendUvarint(buf, m.Slot)
	}
	if m.Filter != "" {
		buf = appendString(buf, 13, m.Filter)
	}
	return buf
}

func (m *BundleEntry) Unmarshal(b []byte) error {
	*m = BundleEntry{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *BundleEntry) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.ID = s
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Key = s
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Strategy = s
		case f == 4 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Kind = s
		case f == 5 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.CreationToken = v
		case f == 6 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seq = v
		case f == 7 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Size = v
		case f == 8 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.BaseID = s
		case f == 9 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &Timestamp{}
			}
			if err := m.CreatedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 10 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Version = s
		case f == 11 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			e := &Ref{}
			if err := e.unmarshal(sub); err != nil {
				return err
			}
			m.Tips = append(m.Tips, e)
		case f == 12 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Slot = v
		case f == 13 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Filter = s
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// EncodedSize returns the exact encoded byte length (equals len(Marshal(m)));
// named EncodedSize because the wire field %s.Size claims the identifier.
func (m *BundleEntry) EncodedSize() int { return m.size() }

// ---- FsckReport ----

func (m *FsckReport) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Seq != 0 {
		n += sizeTag(1) + uvarintLen(m.Seq)
	}
	if m.At != nil && (m.At.Seconds != 0 || m.At.Nanos != 0) {
		n += sizeSub(m.At)
	}
	if m.Host != "" {
		n += sizeTag(3) + sizeLen(len(m.Host)) + len(m.Host)
	}
	for _, s := range m.Missing {
		n += sizeTag(4) + sizeLen(len(s)) + len(s)
	}
	if m.MissingTotal != 0 {
		n += sizeTag(5) + uvarintLen(m.MissingTotal)
	}
	if m.Problems != 0 {
		n += sizeTag(6) + uvarintLen(m.Problems)
	}
	if m.ElapsedSecs != 0 {
		n += sizeTag(7) + 8
	}
	if m.RepairedSeq != 0 {
		n += sizeTag(8) + uvarintLen(m.RepairedSeq)
	}
	return n
}

func (m *FsckReport) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *FsckReport) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Seq != 0 {
		buf = binary.AppendUvarint(buf, uint64(1)<<3|0)
		buf = binary.AppendUvarint(buf, m.Seq)
	}
	if m.At != nil && (m.At.Seconds != 0 || m.At.Nanos != 0) {
		buf = appendSub(buf, 2, m.At)
	}
	if m.Host != "" {
		buf = appendString(buf, 3, m.Host)
	}
	for _, s := range m.Missing {
		buf = appendString(buf, 4, s)
	}
	if m.MissingTotal != 0 {
		buf = binary.AppendUvarint(buf, uint64(5)<<3|0)
		buf = binary.AppendUvarint(buf, m.MissingTotal)
	}
	if m.Problems != 0 {
		buf = binary.AppendUvarint(buf, uint64(6)<<3|0)
		buf = binary.AppendUvarint(buf, m.Problems)
	}
	if m.ElapsedSecs != 0 {
		buf = binary.AppendUvarint(buf, uint64(7)<<3|1)
		buf = binary.LittleEndian.AppendUint64(buf, math.Float64bits(m.ElapsedSecs))
	}
	if m.RepairedSeq != 0 {
		buf = binary.AppendUvarint(buf, uint64(8)<<3|0)
		buf = binary.AppendUvarint(buf, m.RepairedSeq)
	}
	return buf
}

func (m *FsckReport) Unmarshal(b []byte) error {
	*m = FsckReport{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *FsckReport) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Seq = v
		case f == 2 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.At == nil {
				m.At = &Timestamp{}
			}
			if err := m.At.unmarshal(sub); err != nil {
				return err
			}
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Host = s
		case f == 4 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Missing = append(m.Missing, s)
		case f == 5 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.MissingTotal = v
		case f == 6 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Problems = v
		case f == 7 && wt == 1:
			m.ElapsedSecs, err = d.f64()
			if err != nil {
				return err
			}
		case f == 8 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.RepairedSeq = v
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *FsckReport) Size() int { return m.size() }

// ---- RepoCatalog ----

func (m *RepoCatalog) size() int {
	if m == nil {
		return 0
	}
	n := 0
	for _, s := range m.Repos {
		n += sizeTag(1) + sizeLen(len(s)) + len(s)
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		n += sizeSub(m.UpdatedAt)
	}
	return n
}

func (m *RepoCatalog) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *RepoCatalog) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	for _, s := range m.Repos {
		buf = appendString(buf, 1, s)
	}
	if m.UpdatedAt != nil && (m.UpdatedAt.Seconds != 0 || m.UpdatedAt.Nanos != 0) {
		buf = appendSub(buf, 2, m.UpdatedAt)
	}
	return buf
}

func (m *RepoCatalog) Unmarshal(b []byte) error {
	*m = RepoCatalog{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *RepoCatalog) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Repos = append(m.Repos, s)
		case f == 2 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = &Timestamp{}
			}
			if err := m.UpdatedAt.unmarshal(sub); err != nil {
				return err
			}
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *RepoCatalog) Size() int { return m.size() }

// ---- MaintainerHeartbeat ----

func (m *MaintainerHeartbeat) size() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Host != "" {
		n += sizeTag(1) + sizeLen(len(m.Host)) + len(m.Host)
	}
	for _, s := range m.Repos {
		n += sizeTag(2) + sizeLen(len(s)) + len(s)
	}
	for _, s := range m.Exclude {
		n += sizeTag(3) + sizeLen(len(s)) + len(s)
	}
	if m.MaxPackByte != 0 {
		n += sizeTag(4) + uvarintLen(m.MaxPackByte)
	}
	if m.Disk != "" {
		n += sizeTag(5) + sizeLen(len(m.Disk)) + len(m.Disk)
	}
	if m.StartedAt != nil && (m.StartedAt.Seconds != 0 || m.StartedAt.Nanos != 0) {
		n += sizeSub(m.StartedAt)
	}
	if m.LastPassAt != nil && (m.LastPassAt.Seconds != 0 || m.LastPassAt.Nanos != 0) {
		n += sizeSub(m.LastPassAt)
	}
	if m.LastUnit != "" {
		n += sizeTag(8) + sizeLen(len(m.LastUnit)) + len(m.LastUnit)
	}
	if m.Passes != 0 {
		n += sizeTag(9) + uvarintLen(m.Passes)
	}
	return n
}

func (m *MaintainerHeartbeat) Marshal() []byte {
	buf := make([]byte, 0, m.size())
	return m.AppendTo(buf)
}

func (m *MaintainerHeartbeat) AppendTo(buf []byte) []byte {
	if m == nil {
		return buf
	}
	if m.Host != "" {
		buf = appendString(buf, 1, m.Host)
	}
	for _, s := range m.Repos {
		buf = appendString(buf, 2, s)
	}
	for _, s := range m.Exclude {
		buf = appendString(buf, 3, s)
	}
	if m.MaxPackByte != 0 {
		buf = binary.AppendUvarint(buf, uint64(4)<<3|0)
		buf = binary.AppendUvarint(buf, m.MaxPackByte)
	}
	if m.Disk != "" {
		buf = appendString(buf, 5, m.Disk)
	}
	if m.StartedAt != nil && (m.StartedAt.Seconds != 0 || m.StartedAt.Nanos != 0) {
		buf = appendSub(buf, 6, m.StartedAt)
	}
	if m.LastPassAt != nil && (m.LastPassAt.Seconds != 0 || m.LastPassAt.Nanos != 0) {
		buf = appendSub(buf, 7, m.LastPassAt)
	}
	if m.LastUnit != "" {
		buf = appendString(buf, 8, m.LastUnit)
	}
	if m.Passes != 0 {
		buf = binary.AppendUvarint(buf, uint64(9)<<3|0)
		buf = binary.AppendUvarint(buf, m.Passes)
	}
	return buf
}

func (m *MaintainerHeartbeat) Unmarshal(b []byte) error {
	*m = MaintainerHeartbeat{}
	return m.unmarshal(b)
}

// unmarshal decodes b into m without resetting it first (proto3 singular-message merge:
// a repeated field occurrence merges field-granular, last wins — §2.3.1).
func (m *MaintainerHeartbeat) unmarshal(b []byte) error {
	d := &dec{b: b}
	for d.more() {
		f, wt, err := d.tag()
		if err != nil {
			return err
		}
		switch {
		case f == 1 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Host = s
		case f == 2 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Repos = append(m.Repos, s)
		case f == 3 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Exclude = append(m.Exclude, s)
		case f == 4 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.MaxPackByte = v
		case f == 5 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.Disk = s
		case f == 6 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.StartedAt == nil {
				m.StartedAt = &Timestamp{}
			}
			if err := m.StartedAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 7 && wt == 2:
			sub, err := d.raw()
			if err != nil {
				return err
			}
			if m.LastPassAt == nil {
				m.LastPassAt = &Timestamp{}
			}
			if err := m.LastPassAt.unmarshal(sub); err != nil {
				return err
			}
		case f == 8 && wt == 2:
			s, err := d.str()
			if err != nil {
				return err
			}
			m.LastUnit = s
		case f == 9 && wt == 0:
			v, err := d.uvarint()
			if err != nil {
				return err
			}
			m.Passes = v
		default:
			if err := d.skip(wt); err != nil {
				return err
			}
		}
	}
	return nil
}

// Size returns the exact encoded byte length (equals len(Marshal(m))).
func (m *MaintainerHeartbeat) Size() int { return m.size() }

// ---- log framing typed wrappers (§2.4) ----

// AppendEntries appends the uvarint-prefixed frames for entries to buf (zero-allocation
// append style; the returned slice owns the bytes).
func AppendEntries(buf []byte, entries []*LogEntry) []byte {
	for _, e := range entries {
		if e == nil {
			continue
		}
		buf = store.AppendFrame(buf, e.Marshal())
	}
	return buf
}

// DecodeEntries streams frames from r, invoking cb per complete LogEntry.
// Returns (n, err): n = complete frames consumed. A partial trailing frame is NOT an error
// (appendable zonal segments may be read while growing); a corrupt COMPLETE frame surfaces
// as store.ErrCorruptFrame.
func DecodeEntries(r io.Reader, cb func(*LogEntry) error) (int, error) {
	return store.DecodeFrames(r, func(body []byte) error {
		e := &LogEntry{}
		if err := e.Unmarshal(body); err != nil {
			return err
		}
		return cb(e)
	})
}

// DecodeSegment decodes all frames of a sealed segment. A sealed segment has no partial
// tail: any incomplete trailing data is store.ErrCorruptFrame.
func DecodeSegment(b []byte) ([]*LogEntry, error) {
	var out []*LogEntry
	pos := 0
	for pos < len(b) {
		ln := 0
		shift := uint(0)
		for {
			if pos >= len(b) || shift >= 64 {
				return out, fmt.Errorf("%w: truncated frame length", store.ErrCorruptFrame)
			}
			c := b[pos]
			pos++
			ln |= int(c&0x7f) << shift
			shift += 7
			if c < 0x80 {
				break
			}
		}
		if ln > store.MaxFrameBytes {
			return out, fmt.Errorf("%w: frame length %d exceeds %d", store.ErrCorruptFrame, ln, store.MaxFrameBytes)
		}
		if pos+ln > len(b) {
			return out, fmt.Errorf("%w: partial trailing frame in sealed segment", store.ErrCorruptFrame)
		}
		e := &LogEntry{}
		if err := e.Unmarshal(b[pos : pos+ln]); err != nil {
			return out, fmt.Errorf("%w at frame %d: %v", store.ErrCorruptFrame, len(out), err)
		}
		pos += ln
		out = append(out, e)
	}
	return out, nil
}

// EncodeSegment returns the one-shot framed encoding of a sealed segment.
func EncodeSegment(entries []*LogEntry) []byte {
	return AppendEntries(nil, entries)
}

// Marshal returns the framed segment encoding (in-memory form of LogSegment).
func (s *LogSegment) Marshal() []byte {
	if s == nil {
		return nil
	}
	return EncodeSegment(s.Entries)
}

// Unmarshal decodes a sealed framed segment; a partial trailing tail is corrupt here.
func (s *LogSegment) Unmarshal(b []byte) error {
	entries, err := DecodeSegment(b)
	if err != nil {
		return err
	}
	s.Entries = entries
	return nil
}

// ---- convenience unmarshalers for store.CasUpdate call sites ----

// UnmarshalBundleList decodes a bundles/list.pb body (doc 02 §2.7).
func UnmarshalBundleList(b []byte) (*BundleList, error) {
	v := &BundleList{}
	if err := v.Unmarshal(b); err != nil {
		return nil, err
	}
	return v, nil
}

// UnmarshalManifest decodes a manifest.pb body.
func UnmarshalManifest(b []byte) (*Manifest, error) {
	v := &Manifest{}
	if err := v.Unmarshal(b); err != nil {
		return nil, err
	}
	return v, nil
}
