// Package store defines the ObjectStore contract (02_storage_protobuf.md §2.6, from
// MASTER_RUST_SPEC §4.1) — the one interface every backend implements and every caller uses.
//
// CONTRACT FILE: frozen types. Implementers add new files; they do not edit this file
// except through a spec amendment.
package store

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"
)

// Version is an opaque CAS token. GCS = object generation (decimal string);
// S3 = ETag with quotes stripped; memory = global counter; filesystem = "<size>:<mtime_ns>".
// Callers compare for equality only; NEVER parse it.
type Version string

// AccelTarget is what a trusted edge uses to fetch one object (§8.6).
type AccelTarget struct {
	URL           string
	Authorization string // optional bearer; empty = not set
}

// ObjectMeta describes one stored object.
type ObjectMeta struct {
	Key     string
	Size    int64   // whole object size, even for range reads
	Version Version // "" for backends with no versioning
}

// GetOptions shapes a Get.
type GetOptions struct {
	IfNoneMatch Version   // equal → NotModified (304-style)
	IfMatch     Version   // different → ErrKindPreconditionFailed
	Range       *[2]int64 // half-open [start, end); nil = whole object
}

// GetResult is the discriminated union returned by Get.
type GetResult interface{ isGetResult() }

// NotModified reports the conditional get matched the known version.
type NotModified struct{ Version Version }

// Object is a full (or ranged) body.
type Object struct {
	Meta ObjectMeta
	Body io.ReadCloser // caller closes
}

func (NotModified) isGetResult() {}
func (Object) isGetResult()     {}

// PutMode is the write discipline.
type PutMode int

const (
	PutOverwrite PutMode = iota // default
	PutCreate                   // only if absent (create-if-absent; 412-style on exists)
	PutUpdate                   // CAS: only if current version equals PutOptions.IfVersion
)

// PutOptions carries the write discipline and caching hints.
type PutOptions struct {
	Mode        PutMode
	IfVersion   Version // required for PutUpdate, ignored otherwise
	ContentType string
	Immutable   bool // ⇒ long cache headers on HTTP-exposed backends
}

// PutBody is the payload. Exactly one variant is set.
type PutBody struct {
	Bytes     []byte
	Stream    io.Reader // KNOWN length required (StreamLen > 0)
	StreamLen int64
	File      string // local path, streamed by the backend
}

// PutResult is what a successful Put returns.
type PutResult struct{ Meta ObjectMeta }

// ObjectStore is the bucket abstraction. Backends: gcs, s3, memory, filesystem.
type ObjectStore interface {
	Backend() string // "gcs" | "s3" | "memory" | "filesystem"

	Get(ctx context.Context, key string, opts GetOptions) (GetResult, error)
	Head(ctx context.Context, key string) (*ObjectMeta, error) // nil = absent
	Put(ctx context.Context, key string, body PutBody, opts PutOptions) (ObjectMeta, error)
	// Delete is CAS: with ifVersion != "" it deletes only if the version matches.
	// Unconditional delete of an absent key is Ok (no error).
	Delete(ctx context.Context, key string, ifVersion Version) error

	// List streams ObjectMeta lexicographically, strictly after startAfter.
	List(ctx context.Context, prefix, startAfter string, fn func(ObjectMeta) error) error
	// ListPrefixes invokes fn with each distinct "<prefix><segment>/" (delimiter listing), sorted.
	ListPrefixes(ctx context.Context, prefix string, fn func(string) error) error

	// SignedGetURL is a presigned direct-download URL; nil if unsupported/signing fails.
	SignedGetURL(ctx context.Context, key string, ttl time.Duration) (*string, error)
	// AccelTarget is the edge-offload target (§8.6); nil if unsupported.
	AccelTarget(ctx context.Context, key string) (*AccelTarget, error)

	SupportsCompose() bool
	ComposeIsNative() bool
	// Compose: server-side concat of 1..=32 sources, in order, into dst.
	// Sources are left in place; honors opts.Mode on dst.
	Compose(ctx context.Context, dst string, sources []string, opts PutOptions) (ObjectMeta, error)
}

// ---- errors (02_storage_protobuf.md §2.6) ----

type StoreErrorKind int

const (
	ErrKindNotFound StoreErrorKind = iota
	ErrKindPreconditionFailed
	ErrKindRetryable
	ErrKindInvalidArgument
	ErrKindOther
	ErrKindCorrupt
)

type StoreError struct {
	Kind    StoreErrorKind
	Key     string
	Current Version // PreconditionFailed: the version that beat the CAS, if known
	Err     error   // underlying cause, if any
}

func (e *StoreError) Error() string {
	switch e.Kind {
	case ErrKindNotFound:
		return fmt.Sprintf("object not found: %s", e.Key)
	case ErrKindPreconditionFailed:
		return fmt.Sprintf("precondition failed: %s (current=%q)", e.Key, e.Current)
	case ErrKindRetryable:
		return fmt.Sprintf("retryable store error: %s: %v", e.Key, e.Err)
	case ErrKindInvalidArgument:
		return fmt.Sprintf("invalid argument: %s", e.Key)
	case ErrKindCorrupt:
		return fmt.Sprintf("corrupt: %s: %v", e.Key, e.Err)
	default:
		return fmt.Sprintf("store error: %s: %v", e.Key, e.Err)
	}
}

func (e *StoreError) Unwrap() error { return e.Err }

func NewNotFound(key string) *StoreError          { return &StoreError{Kind: ErrKindNotFound, Key: key} }
func NewPrecondition(key string, cur Version) *StoreError {
	return &StoreError{Kind: ErrKindPreconditionFailed, Key: key, Current: cur}
}
func NewRetryable(key string, err error) *StoreError { return &StoreError{Kind: ErrKindRetryable, Key: key, Err: err} }
func NewInvalid(key string, err error) *StoreError   { return &StoreError{Kind: ErrKindInvalidArgument, Key: key, Err: err} }
func NewOther(key string, err error) *StoreError     { return &StoreError{Kind: ErrKindOther, Key: key, Err: err} }
func NewCorrupt(key string, err error) *StoreError   { return &StoreError{Kind: ErrKindCorrupt, Key: key, Err: err} }

func IsNotFound(err error) bool             { return kindIs(err, ErrKindNotFound) }
func IsPreconditionFailed(err error) bool   { return kindIs(err, ErrKindPreconditionFailed) }
func IsRetryable(err error) bool            { return kindIs(err, ErrKindRetryable) }
func IsInvalidArgument(err error) bool      { return kindIs(err, ErrKindInvalidArgument) }
func IsCorrupt(err error) bool              { return kindIs(err, ErrKindCorrupt) }

func kindIs(err error, k StoreErrorKind) bool {
	for err != nil {
		if se, ok := err.(*StoreError); ok {
			return se.Kind == k
		}
		u, ok := err.(interface{ Unwrap() error })
		if !ok {
			return false
		}
		err = u.Unwrap()
	}
	return false
}

// PreconditionCurrent returns the observed version on a CAS loss, if the backend reported it.
func PreconditionCurrent(err error) (Version, bool) {
	if se, ok := err.(*StoreError); ok && se.Kind == ErrKindPreconditionFailed {
		return se.Current, true
	}
	return "", false
}

// ---- extensions (package-level helpers over the interface) ----

// GetBytes reads the whole object. Returns (nil meta, nil err) when absent.
func GetBytes(ctx context.Context, s ObjectStore, key string, opts GetOptions) ([]byte, ObjectMeta, error) {
	res, err := s.Get(ctx, key, opts)
	if err != nil {
		return nil, ObjectMeta{}, err
	}
	switch r := res.(type) {
	case NotModified:
		return nil, ObjectMeta{Key: key, Version: r.Version}, nil
	case Object:
		defer r.Body.Close()
		b, err := io.ReadAll(r.Body)
		if err != nil {
			return nil, r.Meta, &StoreError{Kind: ErrKindRetryable, Key: key, Err: err}
		}
		return b, r.Meta, nil
	default:
		return nil, ObjectMeta{}, &StoreError{Kind: ErrKindOther, Key: key, Err: fmt.Errorf("unknown GetResult variant %T", res)}
	}
}

// GetIfChanged maps a conditional get to (nil, nil) when unchanged; NotFound on a deleted
// object surfaces as a StoreError (caller decides absent-vs-unchanged via IsNotFound).
func GetIfChanged(ctx context.Context, s ObjectStore, key string, known Version) (GetResult, error) {
	return s.Get(ctx, key, GetOptions{IfNoneMatch: known})
}

// PutBytes puts bytes with the given mode.
func PutBytes(ctx context.Context, s ObjectStore, key string, b []byte, opts PutOptions) (ObjectMeta, error) {
	return s.Put(ctx, key, PutBody{Bytes: b}, opts)
}

// Exists reports whether the key is present (HEAD).
func Exists(ctx context.Context, s ObjectStore, key string) (bool, error) {
	m, err := s.Head(ctx, key)
	if err != nil {
		return false, err
	}
	return m != nil, nil
}

// ---- Prefixed wrapper (§4.1: all keys carry the configured store.prefix) ----

// Prefixed wraps a backend and prepends prefix (normalized to end with "/") to every key.
type Prefixed struct {
	Inner  ObjectStore
	Prefix string // "" or "p/"
}

// NewPrefixed normalizes the prefix and wraps inner. Empty prefix returns inner unchanged.
func NewPrefixed(inner ObjectStore, prefix string) ObjectStore {
	prefix = strings.Trim(prefix, "/")
	if prefix == "" {
		return inner
	}
	return &Prefixed{Inner: inner, Prefix: prefix + "/"}
}

func (p *Prefixed) full(key string) string { return p.Prefix + key }
func (p *Prefixed) Backend() string        { return p.Inner.Backend() }

func (p *Prefixed) Get(ctx context.Context, key string, opts GetOptions) (GetResult, error) {
	res, err := p.Inner.Get(ctx, p.full(key), opts)
	if o, ok := res.(Object); ok {
		o.Meta.Key = key
		res = o
	}
	return res, err
}

func (p *Prefixed) Head(ctx context.Context, key string) (*ObjectMeta, error) {
	m, err := p.Inner.Head(ctx, p.full(key))
	if m != nil {
		m.Key = key
	}
	return m, err
}

func (p *Prefixed) Put(ctx context.Context, key string, body PutBody, opts PutOptions) (ObjectMeta, error) {
	m, err := p.Inner.Put(ctx, p.full(key), body, opts)
	m.Key = key
	return m, err
}

func (p *Prefixed) Delete(ctx context.Context, key string, ifVersion Version) error {
	return p.Inner.Delete(ctx, p.full(key), ifVersion)
}

func (p *Prefixed) List(ctx context.Context, prefix, startAfter string, fn func(ObjectMeta) error) error {
	return p.Inner.List(ctx, p.full(prefix), p.full(startAfter), func(m ObjectMeta) error {
		m.Key = strings.TrimPrefix(m.Key, p.Prefix)
		return fn(m)
	})
}

func (p *Prefixed) ListPrefixes(ctx context.Context, prefix string, fn func(string) error) error {
	return p.Inner.ListPrefixes(ctx, p.full(prefix), func(pp string) error {
		return fn(strings.TrimPrefix(pp, p.Prefix))
	})
}

func (p *Prefixed) SignedGetURL(ctx context.Context, key string, ttl time.Duration) (*string, error) {
	return p.Inner.SignedGetURL(ctx, p.full(key), ttl)
}

func (p *Prefixed) AccelTarget(ctx context.Context, key string) (*AccelTarget, error) {
	return p.Inner.AccelTarget(ctx, p.full(key))
}

func (p *Prefixed) SupportsCompose() bool  { return p.Inner.SupportsCompose() }
func (p *Prefixed) ComposeIsNative() bool  { return p.Inner.ComposeIsNative() }

func (p *Prefixed) Compose(ctx context.Context, dst string, sources []string, opts PutOptions) (ObjectMeta, error) {
	full := make([]string, len(sources))
	for i, s := range sources {
		full[i] = p.full(s)
	}
	m, err := p.Inner.Compose(ctx, p.full(dst), full, opts)
	m.Key = dst
	return m, err
}

// IsBulkKey classifies control-plane vs bulk keys (§4.2). Keys whose last path segment ends
// ".pb" or ".json" are control plane; keys under wal/, bundles/, lfs/ are bulk.
func IsBulkKey(key string) bool {
	seg := key
	if i := strings.LastIndexByte(key, '/'); i >= 0 {
		seg = key[i+1:]
	}
	if strings.HasSuffix(seg, ".pb") || strings.HasSuffix(seg, ".json") {
		return false
	}
	return strings.HasPrefix(key, "wal/") || strings.HasPrefix(key, "bundles/") || strings.HasPrefix(key, "lfs/")
}
